// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/soner3/flora/examples/99_webapp/config"
	"github.com/soner3/flora/examples/99_webapp/controller"
	"github.com/soner3/flora/examples/99_webapp/infrastructure"
	"github.com/soner3/flora/examples/99_webapp/middleware"
	"github.com/soner3/flora/examples/99_webapp/repository"
	"github.com/soner3/flora/examples/99_webapp/service"
	"net/http"
)

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	appConfig := config.NewAppConfig()
	db, cleanup, err := Provide_DBConfig_ProvideDatabase(appConfig)
	if err != nil {
		return nil, nil, err
	}
	bookRepository := repository.NewBookRepository(db)
	bookService := service.NewBookService(bookRepository)
	bookHandler := controller.NewBookHandler(bookService)
	helloHandler := controller.NewHelloHandler()
	floraAlias_Provide_MiddlewareConfig_ProvideLogger := Provide_MiddlewareConfig_ProvideLogger()
	floraAlias_Provide_MiddlewareConfig_ProvideAuth := Provide_MiddlewareConfig_ProvideAuth(bookRepository)
	v := ProvideSliceOfController(bookHandler, helloHandler)
	v2 := ProvideSliceOfMiddleware(floraAlias_Provide_MiddlewareConfig_ProvideLogger, floraAlias_Provide_MiddlewareConfig_ProvideAuth)
	handler := Provide_WebConfig_ProvideRouter(v, v2)
	server, cleanup2, err := Provide_WebConfig_ProvideServer(appConfig, handler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	floraContainer := &FloraContainer{
		AppConfig:                              appConfig,
		BookRepository:                         bookRepository,
		BookService:                            bookService,
		BookHandler:                            bookHandler,
		HelloHandler:                           helloHandler,
		DB:                                     db,
		Provide_MiddlewareConfig_ProvideLogger: floraAlias_Provide_MiddlewareConfig_ProvideLogger,
		Provide_MiddlewareConfig_ProvideAuth:   floraAlias_Provide_MiddlewareConfig_ProvideAuth,
		Handler:                                handler,
		Server:                                 server,
		SliceOfController:                      v,
		SliceOfMiddleware:                      v2,
	}
	return floraContainer, func() {
		cleanup2()
		cleanup()
	}, nil
}

// flora_injector.go:

func Provide_DBConfig_ProvideDatabase(p0 *config.AppConfig) (*sql.DB, func(), error) {
	cfg := infrastructure.DBConfig{}

	val, cleanup, err := cfg.ProvideDatabase(p0)
	return val, cleanup, err

}

type FloraAlias_Provide_MiddlewareConfig_ProvideLogger middleware.Middleware

func Provide_MiddlewareConfig_ProvideLogger() FloraAlias_Provide_MiddlewareConfig_ProvideLogger {
	cfg := middleware.MiddlewareConfig{}

	val := cfg.ProvideLogger()
	return FloraAlias_Provide_MiddlewareConfig_ProvideLogger(val)

}

type FloraAlias_Provide_MiddlewareConfig_ProvideAuth middleware.Middleware

func Provide_MiddlewareConfig_ProvideAuth(p0 *repository.BookRepository) FloraAlias_Provide_MiddlewareConfig_ProvideAuth {
	cfg := middleware.MiddlewareConfig{}

	val := cfg.ProvideAuth(p0)
	return FloraAlias_Provide_MiddlewareConfig_ProvideAuth(val)

}

func Provide_WebConfig_ProvideRouter(p0 []controller.Controller, p1 []middleware.Middleware) http.Handler {
	cfg := WebConfig{}

	val := cfg.ProvideRouter(p0, p1)
	return val

}

func Provide_WebConfig_ProvideServer(p0 *config.AppConfig, p1 http.Handler) (*http.Server, func(), error) {
	cfg := WebConfig{}

	val, cleanup, err := cfg.ProvideServer(p0, p1)
	return val, cleanup, err

}

func ProvideSliceOfController(p0 *controller.BookHandler, p1 *controller.HelloHandler) []controller.Controller {
	return []controller.Controller{
		p0, p1,
	}
}

func ProvideSliceOfMiddleware(p0 FloraAlias_Provide_MiddlewareConfig_ProvideLogger, p1 FloraAlias_Provide_MiddlewareConfig_ProvideAuth) []middleware.Middleware {
	return []middleware.Middleware{middleware.Middleware(p0), middleware.Middleware(p1)}
}

type FloraContainer struct {
	AppConfig *config.AppConfig

	BookRepository *repository.BookRepository

	BookService *service.BookService

	BookHandler *controller.BookHandler

	HelloHandler *controller.HelloHandler

	DB *sql.DB

	Provide_MiddlewareConfig_ProvideLogger FloraAlias_Provide_MiddlewareConfig_ProvideLogger

	Provide_MiddlewareConfig_ProvideAuth FloraAlias_Provide_MiddlewareConfig_ProvideAuth

	Handler http.Handler

	Server *http.Server

	SliceOfController []controller.Controller

	SliceOfMiddleware []middleware.Middleware
}
