// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/soner3/flora/example/config"
	"github.com/soner3/flora/example/domain"
	"github.com/soner3/flora/example/mysql"
	"github.com/soner3/flora/example/plugin"
	"github.com/soner3/flora/example/postgres"
)

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, error) {
	configConfig := config.NewConfig()
	postgresRepository := postgres.NewPostgresRepository(configConfig)
	userService := domain.BuildUserService(postgresRepository, configConfig)
	mysqlRepository := mysql.NewMysqlRepository(configConfig)
	loggerPlugin := plugin.NewLoggerPlugin()
	metricsPlugin := plugin.NewMetricsPlugin()
	v := ProvideSliceOfPlugin(loggerPlugin, metricsPlugin)
	pluginManager := plugin.NewPluginManager(v)
	floraContainer := &FloraContainer{
		Config:             configConfig,
		UserService:        userService,
		MysqlRepository:    mysqlRepository,
		PostgresRepository: postgresRepository,
		LoggerPlugin:       loggerPlugin,
		MetricsPlugin:      metricsPlugin,
		PluginManager:      pluginManager,
		SliceOfPlugin:      v,
	}
	return floraContainer, nil
}

// flora_injector.go:

func ProvideSliceOfPlugin(p0 *plugin.LoggerPlugin, p1 *plugin.MetricsPlugin) []plugin.Plugin {
	return []plugin.Plugin{
		p0, p1,
	}
}

type FloraContainer struct {
	Config config.Config

	UserService *domain.UserService

	MysqlRepository *mysql.MysqlRepository

	PostgresRepository *postgres.PostgresRepository

	LoggerPlugin *plugin.LoggerPlugin

	MetricsPlugin *plugin.MetricsPlugin

	PluginManager *plugin.PluginManager

	SliceOfPlugin []plugin.Plugin
}
