// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/soner3/flora/example/cache"
	"github.com/soner3/flora/example/config"
	"github.com/soner3/flora/example/domain"
	"github.com/soner3/flora/example/mysql"
	"github.com/soner3/flora/example/plugin"
	"github.com/soner3/flora/example/postgres"
	"github.com/soner3/flora/example/report"
)

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	configConfig := config.NewConfig()
	v := ProvidePrototypePdfGeneratorAsDocumentGenerator(configConfig)
	reportService := domain.NewReportService(v)
	postgresRepository, cleanup, err := postgres.NewPostgresRepository(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userService := domain.BuildUserService(postgresRepository, configConfig)
	mysqlRepository, cleanup2, err := mysql.NewMysqlRepository(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerPlugin := plugin.NewLoggerPlugin()
	metricsPlugin := plugin.NewMetricsPlugin()
	v2 := ProvideSliceOfPlugin(loggerPlugin, metricsPlugin)
	pluginManager := plugin.NewPluginManager(v2)
	redisClient, cleanup3, err := Provide_CacheConfig_ProvideRedisClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup4, err := Provide_CacheConfig_ProvideDefaultClient(redisClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v3 := ProvidePrototypeNonPrimaryDocumentGenerator(configConfig)
	v4 := ProvidePrototypePdfGenerator(configConfig)
	v5 := ProvidePrototype_CacheConfig_ProvideMemoryClient()
	floraContainer := &FloraContainer{
		Config:                             configConfig,
		ReportService:                      reportService,
		UserService:                        userService,
		MysqlRepository:                    mysqlRepository,
		LoggerPlugin:                       loggerPlugin,
		MetricsPlugin:                      metricsPlugin,
		PluginManager:                      pluginManager,
		PostgresRepository:                 postgresRepository,
		RedisClient:                        redisClient,
		Client:                             client,
		NonPrimaryDocumentGeneratorFactory: v3,
		PdfGeneratorFactory:                v4,
		DocumentGeneratorFactory:           v,
		MemoryClientFactory:                v5,
		SliceOfPlugin:                      v2,
	}
	return floraContainer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// flora_injector.go:

func Provide_CacheConfig_ProvideRedisClient() (*cache.RedisClient, func(), error) {
	cfg := cache.CacheConfig{}
	return cfg.ProvideRedisClient()
}

func ProvidePrototype_CacheConfig_ProvideMemoryClient() func() (*cache.MemoryClient, func(), error) {
	return func() (*cache.MemoryClient, func(), error) {
		cfg := cache.CacheConfig{}
		return cfg.ProvideMemoryClient()
	}
}

func Provide_CacheConfig_ProvideDefaultClient(p0 *cache.RedisClient) (cache.Client, func(), error) {
	cfg := cache.CacheConfig{}
	return cfg.ProvideDefaultClient(p0)
}

func ProvidePrototypeNonPrimaryDocumentGenerator(p0 config.Config) func() (*report.NonPrimaryDocumentGenerator, func(), error) {
	return func() (*report.NonPrimaryDocumentGenerator, func(), error) {
		return report.NewNonPrimaryDocumentGenerator(p0)
	}
}

func ProvidePrototypePdfGenerator(p0 config.Config) func() (*report.PdfGenerator, func(), error) {
	return func() (*report.PdfGenerator, func(), error) {
		return report.NewPdfGenerator(p0)
	}
}

func ProvidePrototypePdfGeneratorAsDocumentGenerator(p0 config.Config) func() (report.DocumentGenerator, func(), error) {
	return func() (report.DocumentGenerator, func(), error) {
		return report.NewPdfGenerator(p0)
	}
}

func ProvideSliceOfPlugin(p0 *plugin.LoggerPlugin, p1 *plugin.MetricsPlugin) []plugin.Plugin {
	return []plugin.Plugin{
		p0, p1,
	}
}

type FloraContainer struct {
	Config config.Config

	ReportService *domain.ReportService

	UserService *domain.UserService

	MysqlRepository *mysql.MysqlRepository

	LoggerPlugin *plugin.LoggerPlugin

	MetricsPlugin *plugin.MetricsPlugin

	PluginManager *plugin.PluginManager

	PostgresRepository *postgres.PostgresRepository

	RedisClient *cache.RedisClient

	Client cache.Client

	NonPrimaryDocumentGeneratorFactory func() (*report.NonPrimaryDocumentGenerator, func(), error)

	PdfGeneratorFactory func() (*report.PdfGenerator, func(), error)

	DocumentGeneratorFactory func() (report.DocumentGenerator, func(), error)

	MemoryClientFactory func() (*cache.MemoryClient, func(), error)

	SliceOfPlugin []plugin.Plugin
}
