// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/soner3/weld/example/config"
	"github.com/soner3/weld/example/domain"
	"github.com/soner3/weld/example/mysql"
	"github.com/soner3/weld/example/postgres"
)

// Injectors from weld_injector.go:

// InitializeContainer is generated by weld and resolved by Google Wire.
func InitializeContainer() (*WeldContainer, error) {
	configConfig := config.NewConfig()
	postgresRepository := postgres.NewPostgresRepository(configConfig)
	userService := domain.BuildUserService(postgresRepository, configConfig)
	mysqlRepository := mysql.NewMysqlRepository(configConfig)
	weldContainer := &WeldContainer{
		Config:             configConfig,
		UserService:        userService,
		MysqlRepository:    mysqlRepository,
		PostgresRepository: postgresRepository,
	}
	return weldContainer, nil
}

// weld_injector.go:

// WeldContainer holds all configured dependencies.
type WeldContainer struct {
	Config config.Config

	UserService *domain.UserService

	MysqlRepository *mysql.MysqlRepository

	PostgresRepository *postgres.PostgresRepository
}
