// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package happy

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	a := NewA()
	v := ProvidePrototype_BuildB()
	c := NewC()
	string2 := ProvideWrapper_CleanConfig_ProvideDB()
	cleanService := NewCleanService()
	iface := ProvideBinding_C_As_Iface(c)
	consumer := NewConsumer(iface)
	myRouter := ProvideWrapper_WebConfig_ProvideRouter()
	server := NewServer(myRouter)
	floraContainer := &FloraContainer{
		A:             a,
		BFactory:      v,
		C:             c,
		ProvideDB:     string2,
		CleanService:  cleanService,
		Consumer:      consumer,
		Server:        server,
		ProvideRouter: myRouter,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

func ProvidePrototype_BuildB() func() *B {
	return func() *B {

		return BuildB()

	}
}

func ProvideWrapper_CleanConfig_ProvideDB() string {

	flora_cfg_struct := CleanConfig{}

	val := flora_cfg_struct.ProvideDB()

	return val

}

func ProvideWrapper_WebConfig_ProvideRouter() MyRouter {

	flora_cfg_struct := WebConfig{}

	val := flora_cfg_struct.ProvideRouter()

	return val

}

func ProvideBinding_C_As_Iface(val *C) Iface {
	return (*C)(val)
}

type FloraContainer struct {
	A *A

	BFactory func() *B

	C *C

	ProvideDB string

	CleanService *CleanService

	Consumer *Consumer

	Server *Server

	ProvideRouter MyRouter
}
