// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package weld

import (
	"github.com/soner3/weld/example/domain"
	"github.com/soner3/weld/example/mysql"
	"github.com/soner3/weld/example/postgres"
)

// Injectors from weld_injector.go:

// InitializeContainer is generated by weld and resolved by Google Wire.
func InitializeContainer() (*WeldContainer, error) {
	postgresRepository := postgres.NewPostgresRepository()
	userService := domain.BuildUserService(postgresRepository)
	mysqlRepository := mysql.NewMysqlRepository()
	weldContainer := &WeldContainer{
		UserService:        userService,
		MysqlRepository:    mysqlRepository,
		PostgresRepository: postgresRepository,
	}
	return weldContainer, nil
}

// weld_injector.go:

// WeldContainer holds all configured dependencies.
type WeldContainer struct {
	UserService *domain.UserService

	MysqlRepository *mysql.MysqlRepository

	PostgresRepository *postgres.PostgresRepository
}
