// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	loggerPlugin := NewLoggerPlugin()
	metricsPlugin := NewMetricsPlugin()
	v := ProvideSliceOfPlugin(loggerPlugin, metricsPlugin)
	pluginManager := NewPluginManager(v)
	floraContainer := &FloraContainer{
		LoggerPlugin:  loggerPlugin,
		MetricsPlugin: metricsPlugin,
		PluginManager: pluginManager,
		SliceOfPlugin: v,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

func ProvideSliceOfPlugin(p0 *LoggerPlugin, p1 *MetricsPlugin) []Plugin {
	return []Plugin{
		p0, p1,
	}
}

type FloraContainer struct {
	LoggerPlugin *LoggerPlugin

	MetricsPlugin *MetricsPlugin

	PluginManager *PluginManager

	SliceOfPlugin []Plugin
}
