// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package happy

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	a := NewA()
	v := ProvidePrototype_BuildB()
	c := NewC()
	string2 := ProvideWrapper_CleanConfig_ProvideDB()
	cleanService := NewCleanService()
	iface := ProvideBinding_happy_C_As_Iface(c)
	consumer := NewConsumer(iface)
	myRouter := ProvideWrapper_WebConfig_ProvideRouter()
	server := NewServer(myRouter)
	floraContainer := &FloraContainer{
		Happy_A:                      a,
		Happy_BFactory:               v,
		Happy_C:                      c,
		Happy_string_ProvideDB:       string2,
		Happy_CleanService:           cleanService,
		Happy_Consumer:               consumer,
		Happy_Server:                 server,
		Happy_MyRouter_ProvideRouter: myRouter,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

func ProvidePrototype_BuildB() func() *B {
	return func() *B {

		return BuildB()

	}
}

func ProvideWrapper_CleanConfig_ProvideDB() string {

	flora_cfg_struct := CleanConfig{}

	val := flora_cfg_struct.ProvideDB()

	return val

}

func ProvideWrapper_WebConfig_ProvideRouter() MyRouter {

	flora_cfg_struct := WebConfig{}

	val := flora_cfg_struct.ProvideRouter()

	return val

}

func ProvideBinding_happy_C_As_Iface(val *C) Iface {

	return val

}

type FloraContainer struct {
	Happy_A *A

	Happy_BFactory func() *B

	Happy_C *C

	Happy_string_ProvideDB string

	Happy_CleanService *CleanService

	Happy_Consumer *Consumer

	Happy_Server *Server

	Happy_MyRouter_ProvideRouter MyRouter
}
