// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	v := ProvidePrototypeSession()
	server := NewServer(v)
	floraContainer := &FloraContainer{
		Server:         server,
		SessionFactory: v,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

func ProvidePrototypeSession() func() *Session {
	return func() *Session {
		return NewSession()
	}
}

type FloraContainer struct {
	Server *Server

	SessionFactory func() *Session
}
