// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	v := ProvideWrapper_DatabaseConfig_ProvideTransaction()
	v2 := ProvideWrapper_NewSession()
	server := NewServer(v2, v)
	floraContainer := &FloraContainer{
		ProvideTransactionFactory: v,
		Server:                    server,
		SessionFactory:            v2,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

func ProvideWrapper_DatabaseConfig_ProvideTransaction() func() (*DBTransaction, func(), error) {
	return func() (*DBTransaction, func(), error) {

		flora_cfg_struct := DatabaseConfig{}
		return flora_cfg_struct.ProvideTransaction()

	}
}

func ProvideWrapper_NewSession() func() *Session {
	return func() *Session {

		return NewSession()

	}
}

type FloraContainer struct {
	ProvideTransactionFactory func() (*DBTransaction, func(), error)

	Server *Server

	SessionFactory func() *Session
}
