// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	englishGreeter := NewEnglishGreeter()
	app := NewApp(englishGreeter)
	floraContainer := &FloraContainer{
		App:            app,
		EnglishGreeter: englishGreeter,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

type FloraContainer struct {
	App *App

	EnglishGreeter *EnglishGreeter
}
