package main

import "fmt"

func main() {
	// InitializeContainer is generated by the 'flora generate' command
	container, cleanup, err := InitializeContainer()
	if err != nil {
		panic(err)
	}
	// Always defer the cleanup function to gracefully close resources
	defer cleanup()

	fmt.Println("Starting the application...")

	// The container holds our fully wired 'App' component
	container.App.Run()
}
