// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	externalLogger, cleanup, err := Provide_AppConfig_ProvideExternalLogger()
	if err != nil {
		return nil, nil, err
	}
	worker := NewWorker(externalLogger)
	floraContainer := &FloraContainer{
		ExternalLogger: externalLogger,
		Worker:         worker,
	}
	return floraContainer, func() {
		cleanup()
	}, nil
}

// flora_injector.go:

func Provide_AppConfig_ProvideExternalLogger() (*ExternalLogger, func(), error) {
	cfg := AppConfig{}
	return cfg.ProvideExternalLogger()
}

type FloraContainer struct {
	ExternalLogger *ExternalLogger

	Worker *Worker
}
