// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/soner3/flora/examples/99_webapp/config"
	"github.com/soner3/flora/examples/99_webapp/controller"
	"github.com/soner3/flora/examples/99_webapp/infrastructure"
	"github.com/soner3/flora/examples/99_webapp/middleware"
	"github.com/soner3/flora/examples/99_webapp/repository"
	"github.com/soner3/flora/examples/99_webapp/service"
	"net/http"
)

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	appConfig := config.NewAppConfig()
	floraQualifier_masterDB, cleanup, err := ProvideWrapper_DBConfig_ProvideMasterDB(appConfig)
	if err != nil {
		return nil, nil, err
	}
	floraQualifier_replicaDB, cleanup2, err := ProvideWrapper_DBConfig_ProvideReplicaDB(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bookRepository := ProvideWrapper_NewBookRepository(floraQualifier_masterDB, floraQualifier_replicaDB)
	serviceBookRepository := ProvideBinding_BookRepository_As_BookRepository(bookRepository)
	bookService := service.ProvideBookService(serviceBookRepository)
	bookHandler := controller.NewBookHandler(bookService)
	helloHandler := controller.NewHelloHandler()
	floraQualifier_ProvideLogger := ProvideWrapper_MiddlewareConfig_ProvideLogger()
	floraQualifier_ProvideAuth := ProvideWrapper_MiddlewareConfig_ProvideAuth(bookRepository)
	v := ProvideSliceOfController_Controller(bookHandler, helloHandler)
	v2 := ProvideSliceOfMiddleware_Middleware(floraQualifier_ProvideLogger, floraQualifier_ProvideAuth)
	handler := ProvideWrapper_WebConfig_ProvideRouter(v, v2)
	server, cleanup3, err := ProvideWrapper_WebConfig_ProvideServer(appConfig, handler, floraQualifier_masterDB)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	floraContainer := &FloraContainer{
		AppConfig:      appConfig,
		BookRepository: bookRepository,
		BookService:    bookService,
		BookHandler:    bookHandler,
		HelloHandler:   helloHandler,
		MasterDB:       floraQualifier_masterDB,
		ReplicaDB:      floraQualifier_replicaDB,
		ProvideLogger:  floraQualifier_ProvideLogger,
		ProvideAuth:    floraQualifier_ProvideAuth,
		ProvideRouter:  handler,
		Server:         server,
	}
	return floraContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// flora_injector.go:

type FloraQualifier_ProvideAuth middleware.Middleware

type FloraQualifier_ProvideLogger middleware.Middleware

type FloraQualifier_masterDB *sql.DB

type FloraQualifier_replicaDB *sql.DB

func ProvideWrapper_NewBookRepository(writeDB FloraQualifier_masterDB, readDB FloraQualifier_replicaDB) *repository.BookRepository {

	val := repository.NewBookRepository((*sql.DB)(writeDB), (*sql.DB)(readDB))

	return val

}

func ProvideWrapper_DBConfig_ProvideMasterDB(cfg *config.AppConfig) (FloraQualifier_masterDB, func(), error) {

	flora_cfg_struct := infrastructure.DBConfig{}

	val, cleanup, err := flora_cfg_struct.ProvideMasterDB(cfg)

	return FloraQualifier_masterDB(val), cleanup, err

}

func ProvideWrapper_DBConfig_ProvideReplicaDB(cfg *config.AppConfig) (FloraQualifier_replicaDB, func(), error) {

	flora_cfg_struct := infrastructure.DBConfig{}

	val, cleanup, err := flora_cfg_struct.ProvideReplicaDB(cfg)

	return FloraQualifier_replicaDB(val), cleanup, err

}

func ProvideWrapper_MiddlewareConfig_ProvideLogger() FloraQualifier_ProvideLogger {

	flora_cfg_struct := middleware.MiddlewareConfig{}

	val := flora_cfg_struct.ProvideLogger()

	return FloraQualifier_ProvideLogger(val)

}

func ProvideWrapper_MiddlewareConfig_ProvideAuth(repo *repository.BookRepository) FloraQualifier_ProvideAuth {

	flora_cfg_struct := middleware.MiddlewareConfig{}

	val := flora_cfg_struct.ProvideAuth(repo)

	return FloraQualifier_ProvideAuth(val)

}

func ProvideWrapper_WebConfig_ProvideRouter(controllers []controller.Controller, middlewares []middleware.Middleware) http.Handler {

	flora_cfg_struct := WebConfig{}

	val := flora_cfg_struct.ProvideRouter(controllers, middlewares)

	return val

}

func ProvideWrapper_WebConfig_ProvideServer(cfg *config.AppConfig, handler http.Handler, startupDB FloraQualifier_masterDB) (*http.Server, func(), error) {

	flora_cfg_struct := WebConfig{}

	val, cleanup, err := flora_cfg_struct.ProvideServer(cfg, handler, (*sql.DB)(startupDB))

	return val, cleanup, err

}

func ProvideBinding_BookRepository_As_BookRepository(val *repository.BookRepository) service.BookRepository {
	return (*repository.BookRepository)(val)
}

func ProvideSliceOfController_Controller(p0 *controller.BookHandler, p1 *controller.HelloHandler) []controller.Controller {
	return []controller.Controller{
		(*controller.BookHandler)(p0), (*controller.HelloHandler)(p1),
	}
}

func ProvideSliceOfMiddleware_Middleware(p0 FloraQualifier_ProvideLogger, p1 FloraQualifier_ProvideAuth) []middleware.Middleware {
	return []middleware.Middleware{
		(middleware.Middleware)(p0), (middleware.Middleware)(p1),
	}
}

type FloraContainer struct {
	AppConfig *config.AppConfig

	BookRepository *repository.BookRepository

	BookService *service.BookService

	BookHandler *controller.BookHandler

	HelloHandler *controller.HelloHandler

	MasterDB FloraQualifier_masterDB

	ReplicaDB FloraQualifier_replicaDB

	ProvideLogger FloraQualifier_ProvideLogger

	ProvideAuth FloraQualifier_ProvideAuth

	ProvideRouter http.Handler

	Server *http.Server
}
