// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/soner3/flora/examples/99_webapp/config"
	"github.com/soner3/flora/examples/99_webapp/controller"
	"github.com/soner3/flora/examples/99_webapp/infrastructure"
	"github.com/soner3/flora/examples/99_webapp/middleware"
	"github.com/soner3/flora/examples/99_webapp/repository"
	"github.com/soner3/flora/examples/99_webapp/service"
	"net/http"
)

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	appConfig := config.NewAppConfig()
	floraQualifier_masterDB, cleanup, err := ProvideWrapper_DBConfig_ProvideMasterDB(appConfig)
	if err != nil {
		return nil, nil, err
	}
	floraQualifier_replicaDB, cleanup2, err := ProvideWrapper_DBConfig_ProvideReplicaDB(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bookRepository := ProvideWrapper_NewBookRepository(floraQualifier_masterDB, floraQualifier_replicaDB)
	serviceBookRepository := ProvideBinding_repository_BookRepository_As_BookRepository(bookRepository)
	bookService := service.ProvideBookService(serviceBookRepository)
	bookHandler := controller.NewBookHandler(bookService)
	helloHandler := controller.NewHelloHandler()
	floraQualifier_middleware_Middleware_ProvideLogger := ProvideWrapper_MiddlewareConfig_ProvideLogger()
	floraQualifier_middleware_Middleware_ProvideAuth := ProvideWrapper_MiddlewareConfig_ProvideAuth(bookRepository)
	v := ProvideSliceOfController_Controller(bookHandler, helloHandler)
	v2 := ProvideSliceOfMiddleware_Middleware(floraQualifier_middleware_Middleware_ProvideLogger, floraQualifier_middleware_Middleware_ProvideAuth)
	handler := ProvideWrapper_WebConfig_ProvideRouter(v, v2)
	server, cleanup3, err := ProvideWrapper_WebConfig_ProvideServer(appConfig, handler, floraQualifier_masterDB)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	floraContainer := &FloraContainer{
		Config_AppConfig:                    appConfig,
		Repository_BookRepository:           bookRepository,
		Service_BookService:                 bookService,
		Controller_BookHandler:              bookHandler,
		Controller_HelloHandler:             helloHandler,
		MasterDB:                            floraQualifier_masterDB,
		ReplicaDB:                           floraQualifier_replicaDB,
		Middleware_Middleware_ProvideLogger: floraQualifier_middleware_Middleware_ProvideLogger,
		Middleware_Middleware_ProvideAuth:   floraQualifier_middleware_Middleware_ProvideAuth,
		Http_Handler_ProvideRouter:          handler,
		Server:                              server,
	}
	return floraContainer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// flora_injector.go:

type FloraQualifier_masterDB *sql.DB

type FloraQualifier_middleware_Middleware_ProvideAuth middleware.Middleware

type FloraQualifier_middleware_Middleware_ProvideLogger middleware.Middleware

type FloraQualifier_replicaDB *sql.DB

func ProvideWrapper_NewBookRepository(writeDB FloraQualifier_masterDB, readDB FloraQualifier_replicaDB) *repository.BookRepository {

	val := repository.NewBookRepository((*sql.DB)(writeDB), (*sql.DB)(readDB))

	return val

}

func ProvideWrapper_DBConfig_ProvideMasterDB(cfg *config.AppConfig) (FloraQualifier_masterDB, func(), error) {

	flora_cfg_struct := infrastructure.DBConfig{}

	val, cleanup, err := flora_cfg_struct.ProvideMasterDB(cfg)

	return FloraQualifier_masterDB(val), cleanup, err

}

func ProvideWrapper_DBConfig_ProvideReplicaDB(cfg *config.AppConfig) (FloraQualifier_replicaDB, func(), error) {

	flora_cfg_struct := infrastructure.DBConfig{}

	val, cleanup, err := flora_cfg_struct.ProvideReplicaDB(cfg)

	return FloraQualifier_replicaDB(val), cleanup, err

}

func ProvideWrapper_MiddlewareConfig_ProvideLogger() FloraQualifier_middleware_Middleware_ProvideLogger {

	flora_cfg_struct := middleware.MiddlewareConfig{}

	val := flora_cfg_struct.ProvideLogger()

	return FloraQualifier_middleware_Middleware_ProvideLogger(val)

}

func ProvideWrapper_MiddlewareConfig_ProvideAuth(repo *repository.BookRepository) FloraQualifier_middleware_Middleware_ProvideAuth {

	flora_cfg_struct := middleware.MiddlewareConfig{}

	val := flora_cfg_struct.ProvideAuth(repo)

	return FloraQualifier_middleware_Middleware_ProvideAuth(val)

}

func ProvideWrapper_WebConfig_ProvideRouter(controllers []controller.Controller, middlewares []middleware.Middleware) http.Handler {

	flora_cfg_struct := WebConfig{}

	val := flora_cfg_struct.ProvideRouter(controllers, middlewares)

	return val

}

func ProvideWrapper_WebConfig_ProvideServer(cfg *config.AppConfig, handler http.Handler, startupDB FloraQualifier_masterDB) (*http.Server, func(), error) {

	flora_cfg_struct := WebConfig{}

	val, cleanup, err := flora_cfg_struct.ProvideServer(cfg, handler, (*sql.DB)(startupDB))

	return val, cleanup, err

}

func ProvideBinding_repository_BookRepository_As_BookRepository(val *repository.BookRepository) service.BookRepository {

	return val

}

func ProvideSliceOfController_Controller(p0 *controller.BookHandler, p1 *controller.HelloHandler) []controller.Controller {
	return []controller.Controller{
		p0, p1,
	}
}

func ProvideSliceOfMiddleware_Middleware(p0 FloraQualifier_middleware_Middleware_ProvideLogger, p1 FloraQualifier_middleware_Middleware_ProvideAuth) []middleware.Middleware {
	return []middleware.Middleware{
		(middleware.Middleware)(p0), (middleware.Middleware)(p1),
	}
}

type FloraContainer struct {
	Config_AppConfig *config.AppConfig

	Repository_BookRepository *repository.BookRepository

	Service_BookService *service.BookService

	Controller_BookHandler *controller.BookHandler

	Controller_HelloHandler *controller.HelloHandler

	MasterDB FloraQualifier_masterDB

	ReplicaDB FloraQualifier_replicaDB

	Middleware_Middleware_ProvideLogger FloraQualifier_middleware_Middleware_ProvideLogger

	Middleware_Middleware_ProvideAuth FloraQualifier_middleware_Middleware_ProvideAuth

	Http_Handler_ProvideRouter http.Handler

	Server *http.Server
}
